spring:
  application:
    name: Blog
  datasource:
    url: jdbc:h2:file:./data/DB;DATABASE_TO_UPPER=false
    username: sa
    password:
  h2:
    console:
      path: /db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true